global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "server"
    static_configs:
      - targets: ["server:18080"]

  - job_name: "jaeger"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["jaeger:14268"]
